server:
  port: 8080

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: paciente-service
          uri: http://healthsys-servico-pacientes:8081
          predicates:
            - Path=/paciente/**
            - Path=/paciente

        - id: usuario-service
          uri: http://healthsys-servico-usuarios:8084
          predicates:
            - Path=/usuario/**
            - Path=/usuario

        - id: auth-service
          uri: http://healthsys-servico-usuarios:8084
          predicates:
            - Path=/auth/**
            - Path=/auth

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    root: INFO