server:
  port: 8080

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  cloud:
    discovery:
      enabled: false  # 🔥 desativa discovery (Eureka)
    gateway:
      routes:

        # =========================
        # PACIENTES
        # =========================
        - id: paciente-service
          uri: http://healthsys-servico-pacientes:8081
          predicates:
            - Path=/paciente/**

        # =========================
        # USUARIOS
        # =========================
        - id: usuario-service
          uri: http://healthsys-servico-usuarios:8084
          predicates:
            - Path=/usuario/**

        # =========================
        # AUTH
        # =========================
        - id: auth-service
          uri: http://healthsys-servico-usuarios:8084
          predicates:
            - Path=/auth/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

# =========================
# ACTUATOR
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# =========================
# LOGS
# =========================
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    root: INFO